log_path: /var/log/oeAware
log_level: 2
enable_list:
plugin_list:
  - name: numafast
    description: numafast is a userspace tool designed for Kunpeng Chips that aims to improve 
                 system performance by reducing cross-NUMA memory access.
    url: ""